version: '3.2'

services:
  accounts:
    image: garystafford/storefront-accounts:latest
    # expose:
    # - "8080"
    ports:
    - "8085:8080/tcp"

  orders:
    image: garystafford/storefront-orders:latest
    # expose:
    # - "8080"
    ports:
    - "8090:8080/tcp"

  fulfillment:
    image: garystafford/storefront-fulfillment:latest
    # expose:
    # - "8080"
    ports:
    - "8095:8080/tcp"

  zuul:
    image: garystafford/storefront-zuul:latest
    expose:
    - "8080"
    ports:
    - "8080:8080/tcp"

  eureka:
    image: garystafford/storefront-eureka:latest
    # expose:
    # - "8761"
    ports:
    - "8761:8761/tcp"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
    - "2181"
    ports:
    - "2181:2181/tcp"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    expose:
    - "9092"
    ports:
    - "9092:9092/tcp"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "accounts.customer.change:1:1,fulfillment.order.change:1:1,orders.order.fulfill:1:1"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock

  kafka_manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9000:9000/tcp"
    expose:
    - "9000"
    links:
    - zookeeper
    - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null

  # testapp:
  #   image: openjdk:8u151-jdk-alpine3.7
  #   depends_on:
  #   - kafka
  #   - mongo
  #   ports:
  #   - "8085:8085/tcp"
  #   - "8090:8090/tcp"
  #   - "8095:8095/tcp"
  #   expose:
  #   - "8085"
  #   - "8090"
  #   - "8095"
  #   command: ['sleep', '60000']
