version: '3.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - "2181:2181"
    environment:
      SERVICE_NAME: zookeeper
      SERVICE_TAGS: monitoring
    networks:
    - widget_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker3]
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      SERVICE_NAME: kafka
      SERVICE_TAGS: monitoring
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - widget_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker3]
