version: '3.2'

services:
  accounts:
    image: garystafford/storefront-accounts:latest
    # expose:
    # - "8080"
    # ports:
    # - "8085:8080/tcp"
    depends_on:
    - kafka
    - mongo

  orders:
    image: garystafford/storefront-orders:latest
    # expose:
    # - "8080"
    # ports:
    # - "8090:8080/tcp"
    depends_on:
    - kafka
    - mongo
    - eureka

  fulfillment:
    image: garystafford/storefront-fulfillment:latest
    # expose:
    # - "8080"
    # ports:
    # - "8095:8080/tcp"
    depends_on:
    - kafka
    - mongo
    - eureka

  zuul:
    image: garystafford/storefront-zuul:latest
    expose:
    - "8080"
    ports:
    - "8080:8080/tcp"
    depends_on:
    - kafka
    - mongo
    - eureka

  eureka:
    image: garystafford/storefront-eureka:latest
    # expose:
    # - "8761"
    ports:
    - "8761:8761/tcp"

  mongo:
    image: mongo:latest
    command: --smallfiles
    expose:
    - "27017"
    ports:
    - "27017:27017/tcp"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    # expose:
    # - "2181"
    ports:
    - "2181:2181/tcp"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    # expose:
    # - "9092"
    ports:
    - "9092:9092/tcp"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "accounts.customer.change:1:1,fulfillment.order.change:1:1,orders.order.fulfill:1:1"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"

  kafka_manager:
    image: hlebalbau/kafka-manager:latest
    ports:
    - "9000:9000/tcp"
    expose:
    - "9000"
    depends_on:
    - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
