version: '3.0'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - "2181:2181/tcp"
    environment:
      SERVICE_NAME: zookeeper
      SERVICE_TAGS: monitoring

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    expose:
     - "9092"
    ports:
    - "9092:9092/tcp"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ADVERTISED_PORT: 9092
      SERVICE_NAME: kafka
      SERVICE_TAGS: monitoring
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
