apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-services.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: accounts
  name: accounts
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: accounts
    spec:
      containers:
      - image: garystafford/storefront-accounts:latest
        name: accounts
        resources: {}
      hostname: accounts
      restartPolicy: Always
status: {}
