apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-services.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: fulfillment
  name: fulfillment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fulfillment
    spec:
      containers:
      - image: garystafford/storefront-fulfillment:latest
        name: fulfillment
        resources: {}
      hostname: fulfillment
      restartPolicy: Always
status: {}
