apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-services.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: orders
  name: orders
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orders
    spec:
      containers:
      - image: garystafford/storefront-orders:latest
        name: orders
        resources: {}
      hostname: orders
      restartPolicy: Always
status: {}
