apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ingressgateway
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
  peers:
  - mtls:
  origins:
  - jwt:
      audiences:
      - "https://api.storefront-demo.com/"
      issuer: "https://storefront-demo.auth0.com/"
      jwksUri: "https://storefront-demo.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN
# apiVersion: authentication.istio.io/v1alpha1
# kind: Policy
# metadata:
#   name: accounts-auth-policy
#   namespace: dev
# spec:
#   targets:
#   - name: accounts
#   peers:
#   - mtls:
#   origins:
#   - jwt:
#       audiences:
#       - "https://api.storefront-demo.com/"
#       issuer: "https://storefront-demo.auth0.com/"
#       jwksUri: "https://storefront-demo.auth0.com/.well-known/jwks.json"
#   principalBinding: USE_ORIGIN
