apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: auth-policy-ingressgateway
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
  peers:
  - mtls: {}
  origins:
  - jwt:
      audiences:
      - "https://api.storefront-demo.com/"
      issuer: "https://storefront-demo.auth0.com/"
      jwksUri: "https://storefront-demo.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN
