apiVersion: v1
kind: Service
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: fulfillment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfillment
  template:
    metadata:
      labels:
        app: fulfillment
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: fulfillment
        image: garystafford/storefront-fulfillment:gke-2.1.0
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gke"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://storefront-user:storefront-password@mongodb-release:27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "fulfillment"
        - name: SPRING_DATA_KAFKA_BOOTSTRAP-SERVERS
          value: "kafka:9092"
        - name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent #Always
      restartPolicy: Always
